spring:
  ai:
    openai:
      api-key: ${OPENAI_APIKEY}
      chat:
        options:
          model: gpt-4o-mini
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true